name: Build & Deploy Bisa app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Bisa-api
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run:
          mvn clean
          mvn -B package --file pom.xml